# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "basic-app"
client_id = "63cfeaa92c0d5c49e49a107ee8567597"
application_url = "https://4cc4-103-180-245-254.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://4cc4-103-180-245-254.ngrok-free.app/authenticate" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "ostad-basic-app.myshopify.com"
